#!/usr/bin/env bash
set -u
set -o pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1
source ".githooks/lib/common.sh"

log "[post-merge] Updating submodules"

sync_submodules || {
    log "[post-merge] FAILED to sync submodules"
    exit 1
}
