#!/usr/bin/env bash
set -u
set -o pipefail

checkout_type="${3:-0}"

# Only run on branch checkout
[[ "$checkout_type" != "1" ]] && exit 0

cd "$(git rev-parse --show-toplevel)" || exit 1
# shellcheck disable=1091
source ".githooks/lib/common.sh"

log "[post-checkout] Updating submodules"

sync_submodules || {
    log "[post-checkout] FAILED to sync submodules"
    exit 1
}
